### ISSUE TITLE
Комментарии к слайдам

### ISSUE THREAD

**Issue by maksimr** [cy6erskunk/shower-server#3]
Добавить возможность оставлять комментарии к слайду.
Что бы потом можно было перейти к слайду и вопросу.

**Comment by cy6erskunk** [comment]
Попробую поэкспериментировать в веточке. Сейчас есть проблема с тем, что shower навешивает свои обработчики keydown, поэтому надо либо там что-то менять, либо мой клиентский код раньше грузить

**Comment by miripiruni** [comment]
Можно и в шовере поменять. Ты можешь сформулировать задачу?

**Comment by cy6erskunk** [comment]
Нужно дать возможность прокидывать в обработчик keydown функцию, которая будет отрабатывать до стандартного шоверовского обработчика. И, в зависимости от кода выхода, выполнять стандартный обработчик или нет.
